package com.aprendiz.ragp.proyectopsp4.models;

public class Constants {
    public static final String DATABASE_NAME="psp.db";
    public static final int DATABASE_VERSION=1;

    public static final String TableProject="CREATE TABLE PROYECTO (IDPROYECTO INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT );";
    public static final String TableTimeLog="CREATE TABLE TIMELOG (IDTIMELOG INTEGER PRIMARY KEY AUTOINCREMENT ,PHASE TEXT, START TEXT, INTERRUPCION INTEGER, STOP TEXT, DELTA INTEGER, COMMENTS TEXT, PROYECTO INTEGER, " +
            "FOREIGN KEY (PROYECTO) REFERENCES PROYECTO (IDPROYECTO));";
    public static final String TableDefectLog="CREATE TABLE DEFECTLOG (IDDEFECTLOG INTEGER PRIMARY KEY AUTOINCREMENT,DATE TEXT, TYPE TEXT, FIXTIME TEXT, PHASEI TEXT, PHASER TEXT, COMMENTS TEXT, PROYECTO INTEGER, " +
            "FOREIGN KEY (PROYECTO) REFERENCES PROYECTO(IDPROYECTO));";
    public static final String TablePPS="CREATE TABLE PPS (IDPPS INTEGER PRIMARY KEY AUTOINCREMENT, TIME TEXT, PROYECTO INTEGER, " +
            "FOREIGN KEY (PROYECTO) REFERENCES PROYECTO (IDPROYECTO));";


}
